# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('machineStatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestatus',
            name='machine_status',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
